### ISSUE TITLE
Joining WFCD

### ISSUE THREAD

**Issue by TobiTenno** [Circl3s/WarframeStatus#1]
Any interest in folding this into the community developers org (https://github.com/WFCD) and we can support your efforts with ongoing maintenance?

**Comment by Circl3s** [comment]
@TobiTenno I mean, it's just an API toy I made a long time ago. I lost a bunch of code for new features when I forgot to commit it before formatting my drive and decided there's no point afterwards. lol If you feel like it's worth maintaining then sure!

**Comment by TobiTenno** [comment]
up to you, i was just curious :D if you don't feel there's a point anymore, i totally understand that
